MDScreen:
    name: "new_note"

    BoxLayout:
        orientation: "vertical"

        MDToolbar:
            title: "QNote"
            right_action_items: [["content-save", lambda x: app.save_note(title_box.text,note_box.text)]]

        MDTextField:
            id: title_box
            hint_text: "Title"
            mode: "rectangle"
        
        MDTextFieldRect:
            id: note_box
            hint_text: "Write your note."